import { MigrationInterface, QueryRunner } from "typeorm";

export class UserIdColumnsToUuid1783524572427 implements MigrationInterface {
    name = 'UserIdColumnsToUuid1783524572427'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_leave_audit_entries_occurred"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_balance_changes_user_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_request_activities_request"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp()`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp()`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp()`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp()`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT clock_timestamp()`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP CONSTRAINT "PK_7830ec0c17fac973e076b57ca27"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP COLUMN "decisionId"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD "decisionId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD CONSTRAINT "PK_7830ec0c17fac973e076b57ca27" PRIMARY KEY ("decisionId")`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_approval_decisions_request"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD "requestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP COLUMN "actorUserId"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD "actorUserId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP CONSTRAINT "PK_8063502d2b5e0a28cc8f6c5adb7"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD CONSTRAINT "PK_8063502d2b5e0a28cc8f6c5adb7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP CONSTRAINT "UQ_c8604383da48dc065c6d05606c6"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "activityId"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "activityId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD CONSTRAINT "UQ_c8604383da48dc065c6d05606c6" UNIQUE ("activityId")`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "requestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "employeeId"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "employeeId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "PK_0f69842491cdc23208d6698e0c5"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "PK_7f53ccff9166a0870777b1fd6e3" PRIMARY KEY ("leaveType")`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "PK_7f53ccff9166a0870777b1fd6e3"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "PK_0f69842491cdc23208d6698e0c5" PRIMARY KEY ("leaveType", "userId")`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP CONSTRAINT "PK_19e19dffaa62ded3acd526006ed"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD CONSTRAINT "PK_19e19dffaa62ded3acd526006ed" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "PK_2f7f8dcd4cebd0f0cd6a034911c"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD "requestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "PK_2f7f8dcd4cebd0f0cd6a034911c" PRIMARY KEY ("requestId")`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_requests_requester"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP COLUMN "requesterUserId"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD "requesterUserId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP CONSTRAINT "PK_eee91f91711c732ad912157e377"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD CONSTRAINT "PK_eee91f91711c732ad912157e377" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "requestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "actorUserId"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "actorUserId" uuid`);
        await queryRunner.query(`DROP INDEX "public"."uq_leave_request_approvers_request_email"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP CONSTRAINT "PK_44ad60f495edb9a05ca83c70f78"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD CONSTRAINT "PK_44ad60f495edb9a05ca83c70f78" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "requestId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_8bf09ba754322ab9c22a215c919"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_8bf09ba754322ab9c22a215c919" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "PK_6327cc433074c3efddbe2ba390f"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "PK_ecc9f04daea3e5f057ca85c6611" PRIMARY KEY ("roleName")`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "PK_ecc9f04daea3e5f057ca85c6611"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "PK_6327cc433074c3efddbe2ba390f" PRIMARY KEY ("roleName", "userId")`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "PK_81daeff81f237bd384f7cfc4a4c"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "PK_81daeff81f237bd384f7cfc4a4c" PRIMARY KEY ("id")`);
        await queryRunner.query(`DROP INDEX "public"."idx_notification_deliveries_request"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "requestId" uuid`);
        await queryRunner.query(`CREATE INDEX "idx_leave_approval_decisions_request" ON "leave_approval_decisions" ("requestId") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_audit_entries_occurred" ON "leave_audit_entries" ("occurredAt", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_balance_changes_user_type" ON "leave_balance_changes" ("userId", "leaveType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_requests_requester" ON "leave_requests" ("requesterUserId") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_request_activities_request" ON "leave_request_activities" ("requestId", "createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_leave_request_approvers_request_email" ON "leave_request_approvers" ("requestId", "email") `);
        await queryRunner.query(`CREATE INDEX "idx_user_roles_user" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_notification_deliveries_request" ON "notification_deliveries" ("requestId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."idx_notification_deliveries_request"`);
        await queryRunner.query(`DROP INDEX "public"."idx_user_roles_user"`);
        await queryRunner.query(`DROP INDEX "public"."uq_leave_request_approvers_request_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_request_activities_request"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_requests_requester"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_balance_changes_user_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_audit_entries_occurred"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_approval_decisions_request"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "requestId" character varying`);
        await queryRunner.query(`CREATE INDEX "idx_notification_deliveries_request" ON "notification_deliveries" ("requestId") `);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "PK_81daeff81f237bd384f7cfc4a4c"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "PK_81daeff81f237bd384f7cfc4a4c" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "PK_6327cc433074c3efddbe2ba390f"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "PK_ecc9f04daea3e5f057ca85c6611" PRIMARY KEY ("roleName")`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "PK_ecc9f04daea3e5f057ca85c6611"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "PK_6327cc433074c3efddbe2ba390f" PRIMARY KEY ("roleName", "userId")`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_8bf09ba754322ab9c22a215c919"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_8bf09ba754322ab9c22a215c919" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "requestId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP CONSTRAINT "PK_44ad60f495edb9a05ca83c70f78"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD CONSTRAINT "PK_44ad60f495edb9a05ca83c70f78" PRIMARY KEY ("id")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_leave_request_approvers_request_email" ON "leave_request_approvers" ("email", "requestId") `);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "actorUserId"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "actorUserId" character varying`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "requestId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP CONSTRAINT "PK_eee91f91711c732ad912157e377"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD CONSTRAINT "PK_eee91f91711c732ad912157e377" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP COLUMN "requesterUserId"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD "requesterUserId" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_leave_requests_requester" ON "leave_requests" ("requesterUserId") `);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "PK_2f7f8dcd4cebd0f0cd6a034911c"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD "requestId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "PK_2f7f8dcd4cebd0f0cd6a034911c" PRIMARY KEY ("requestId")`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP CONSTRAINT "PK_19e19dffaa62ded3acd526006ed"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD CONSTRAINT "PK_19e19dffaa62ded3acd526006ed" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "PK_0f69842491cdc23208d6698e0c5"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "PK_7f53ccff9166a0870777b1fd6e3" PRIMARY KEY ("leaveType")`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "PK_7f53ccff9166a0870777b1fd6e3"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "PK_0f69842491cdc23208d6698e0c5" PRIMARY KEY ("leaveType", "userId")`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "employeeId"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "employeeId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "requestId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP CONSTRAINT "UQ_c8604383da48dc065c6d05606c6"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "activityId"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "activityId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD CONSTRAINT "UQ_c8604383da48dc065c6d05606c6" UNIQUE ("activityId")`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP CONSTRAINT "PK_8063502d2b5e0a28cc8f6c5adb7"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" ADD CONSTRAINT "PK_8063502d2b5e0a28cc8f6c5adb7" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP COLUMN "actorUserId"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD "actorUserId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP COLUMN "requestId"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD "requestId" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_leave_approval_decisions_request" ON "leave_approval_decisions" ("requestId") `);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP CONSTRAINT "PK_7830ec0c17fac973e076b57ca27"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP COLUMN "decisionId"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD "decisionId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD CONSTRAINT "PK_7830ec0c17fac973e076b57ca27" PRIMARY KEY ("decisionId")`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "leave_audit_entries" DROP COLUMN "createdAt"`);
        await queryRunner.query(`CREATE INDEX "idx_leave_request_activities_request" ON "leave_request_activities" ("id", "requestId") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_balance_changes_user_type" ON "leave_balance_changes" ("id", "leaveType", "userId") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_audit_entries_occurred" ON "leave_audit_entries" ("id", "occurredAt") `);
    }

}
