import { MigrationInterface, QueryRunner } from "typeorm";

export class UseNativeEnums1783685114115 implements MigrationInterface {
    name = 'UseNativeEnums1783685114115'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "leave_allocations" DROP CONSTRAINT "chk_leave_allocations_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "chk_leave_requests_status"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP CONSTRAINT "chk_leave_requests_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP CONSTRAINT "chk_leave_approval_decisions_action"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP CONSTRAINT "chk_leave_balances_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP CONSTRAINT "chk_leave_balance_changes_reason"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP CONSTRAINT "chk_leave_balance_changes_leave_type"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP CONSTRAINT "chk_leave_request_activities_status_at_event"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP CONSTRAINT "chk_leave_request_approvers_decision"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP CONSTRAINT "chk_leave_request_approvers_kind"`);
        await queryRunner.query(`ALTER TABLE "leave_settings" DROP CONSTRAINT "chk_leave_settings_carryover_policy"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "chk_user_roles_role_name"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP CONSTRAINT "chk_notification_deliveries_status"`);
        await queryRunner.query(`DROP INDEX "public"."uq_leave_allocations_user_year_type"`);
        await queryRunner.query(`ALTER TABLE "leave_allocations" DROP COLUMN "leaveType"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_allocations_leavetype_enum" AS ENUM('vacation', 'sick')`);
        await queryRunner.query(`ALTER TABLE "leave_allocations" ADD "leaveType" "public"."leave_allocations_leavetype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP COLUMN "leaveType"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_leavetype_enum" AS ENUM('vacation', 'sick')`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD "leaveType" "public"."leave_requests_leavetype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_requests_status_enum" AS ENUM('pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD "status" "public"."leave_requests_status_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP COLUMN "action"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_approval_decisions_action_enum" AS ENUM('approve', 'reject')`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD "action" "public"."leave_approval_decisions_action_enum" NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."uq_leave_balances_user_type_year"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP COLUMN "leaveType"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_balances_leavetype_enum" AS ENUM('vacation', 'sick')`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD "leaveType" "public"."leave_balances_leavetype_enum" NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_balance_changes_user_type"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "leaveType"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_balance_changes_leavetype_enum" AS ENUM('vacation', 'sick')`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "leaveType" "public"."leave_balance_changes_leavetype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "reason"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_balance_changes_reason_enum" AS ENUM('accrual', 'hold', 'release', 'spent', 'adjustment')`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "reason" "public"."leave_balance_changes_reason_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "statusAtEvent"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_request_activities_statusatevent_enum" AS ENUM('pending', 'approved', 'rejected', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "statusAtEvent" "public"."leave_request_activities_statusatevent_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "kind"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_request_approvers_kind_enum" AS ENUM('to', 'cc')`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "kind" "public"."leave_request_approvers_kind_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "decision"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_request_approvers_decision_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "decision" "public"."leave_request_approvers_decision_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "leave_settings" DROP COLUMN "carryoverPolicy"`);
        await queryRunner.query(`CREATE TYPE "public"."leave_settings_carryoverpolicy_enum" AS ENUM('none', 'capped', 'full')`);
        await queryRunner.query(`ALTER TABLE "leave_settings" ADD "carryoverPolicy" "public"."leave_settings_carryoverpolicy_enum" NOT NULL DEFAULT 'none'`);
        await queryRunner.query(`DROP INDEX "public"."uq_user_roles_user_role"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "roleName"`);
        await queryRunner.query(`CREATE TYPE "public"."user_roles_rolename_enum" AS ENUM('employee', 'administrator')`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "roleName" "public"."user_roles_rolename_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."notification_deliveries_status_enum" AS ENUM('pending', 'sent', 'failed')`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "status" "public"."notification_deliveries_status_enum" NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_leave_allocations_user_year_type" ON "leave_allocations" ("userId", "year", "leaveType") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_leave_balances_user_type_year" ON "leave_balances" ("userId", "leaveType", "year") `);
        await queryRunner.query(`CREATE INDEX "idx_leave_balance_changes_user_type" ON "leave_balance_changes" ("userId", "leaveType", "year", "createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_user_roles_user_role" ON "user_roles" ("userId", "roleName") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."uq_user_roles_user_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_leave_balance_changes_user_type"`);
        await queryRunner.query(`DROP INDEX "public"."uq_leave_balances_user_type_year"`);
        await queryRunner.query(`DROP INDEX "public"."uq_leave_allocations_user_year_type"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."notification_deliveries_status_enum"`);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP COLUMN "roleName"`);
        await queryRunner.query(`DROP TYPE "public"."user_roles_rolename_enum"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD "roleName" character varying NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_user_roles_user_role" ON "user_roles" ("roleName", "userId") `);
        await queryRunner.query(`ALTER TABLE "leave_settings" DROP COLUMN "carryoverPolicy"`);
        await queryRunner.query(`DROP TYPE "public"."leave_settings_carryoverpolicy_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_settings" ADD "carryoverPolicy" character varying NOT NULL DEFAULT 'none'`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "decision"`);
        await queryRunner.query(`DROP TYPE "public"."leave_request_approvers_decision_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "decision" character varying NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" DROP COLUMN "kind"`);
        await queryRunner.query(`DROP TYPE "public"."leave_request_approvers_kind_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD "kind" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" DROP COLUMN "statusAtEvent"`);
        await queryRunner.query(`DROP TYPE "public"."leave_request_activities_statusatevent_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD "statusAtEvent" character varying`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "reason"`);
        await queryRunner.query(`DROP TYPE "public"."leave_balance_changes_reason_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "reason" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" DROP COLUMN "leaveType"`);
        await queryRunner.query(`DROP TYPE "public"."leave_balance_changes_leavetype_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD "leaveType" character varying NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_leave_balance_changes_user_type" ON "leave_balance_changes" ("createdAt", "leaveType", "userId", "year") `);
        await queryRunner.query(`ALTER TABLE "leave_balances" DROP COLUMN "leaveType"`);
        await queryRunner.query(`DROP TYPE "public"."leave_balances_leavetype_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD "leaveType" character varying NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_leave_balances_user_type_year" ON "leave_balances" ("leaveType", "userId", "year") `);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" DROP COLUMN "action"`);
        await queryRunner.query(`DROP TYPE "public"."leave_approval_decisions_action_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD "action" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_requests" DROP COLUMN "leaveType"`);
        await queryRunner.query(`DROP TYPE "public"."leave_requests_leavetype_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD "leaveType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leave_allocations" DROP COLUMN "leaveType"`);
        await queryRunner.query(`DROP TYPE "public"."leave_allocations_leavetype_enum"`);
        await queryRunner.query(`ALTER TABLE "leave_allocations" ADD "leaveType" character varying NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_leave_allocations_user_year_type" ON "leave_allocations" ("leaveType", "userId", "year") `);
        await queryRunner.query(`ALTER TABLE "notification_deliveries" ADD CONSTRAINT "chk_notification_deliveries_status" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'sent'::character varying, 'failed'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "chk_user_roles_role_name" CHECK ((("roleName")::text = ANY ((ARRAY['employee'::character varying, 'administrator'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_settings" ADD CONSTRAINT "chk_leave_settings_carryover_policy" CHECK ((("carryoverPolicy")::text = ANY ((ARRAY['none'::character varying, 'capped'::character varying, 'full'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD CONSTRAINT "chk_leave_request_approvers_kind" CHECK (((kind)::text = ANY ((ARRAY['to'::character varying, 'cc'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_request_approvers" ADD CONSTRAINT "chk_leave_request_approvers_decision" CHECK (((decision)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_request_activities" ADD CONSTRAINT "chk_leave_request_activities_status_at_event" CHECK ((("statusAtEvent")::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD CONSTRAINT "chk_leave_balance_changes_leave_type" CHECK ((("leaveType")::text = ANY ((ARRAY['vacation'::character varying, 'sick'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_balance_changes" ADD CONSTRAINT "chk_leave_balance_changes_reason" CHECK (((reason)::text = ANY ((ARRAY['accrual'::character varying, 'hold'::character varying, 'release'::character varying, 'spent'::character varying, 'adjustment'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_balances" ADD CONSTRAINT "chk_leave_balances_leave_type" CHECK ((("leaveType")::text = ANY ((ARRAY['vacation'::character varying, 'sick'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_approval_decisions" ADD CONSTRAINT "chk_leave_approval_decisions_action" CHECK (((action)::text = ANY ((ARRAY['approve'::character varying, 'reject'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "chk_leave_requests_leave_type" CHECK ((("leaveType")::text = ANY ((ARRAY['vacation'::character varying, 'sick'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_requests" ADD CONSTRAINT "chk_leave_requests_status" CHECK (((status)::text = ANY ((ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying])::text[])))`);
        await queryRunner.query(`ALTER TABLE "leave_allocations" ADD CONSTRAINT "chk_leave_allocations_leave_type" CHECK ((("leaveType")::text = ANY ((ARRAY['vacation'::character varying, 'sick'::character varying])::text[])))`);
    }

}
